version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:postgres@postgres-test:5432/tradingbot_test
      - DIEGO_URL=http://tests:3000
      - MIGUEL_SERVICE_URL=http://tests:3001
    depends_on:
      postgres-test:
        condition: service_healthy

  postgres-test:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tradingbot_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tradingbot_test"]
      interval: 5s
      timeout: 5s
      retries: 5
